# Generated by Django 3.1.7 on 2021-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='age',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
